name: "theurge.com"
allowed_domains:
  - "theurge.com"
start_pages: 
  - "https://theurge.com/men/search/?cat=clothing-t-shirts"
  - "https://theurge.com/women/search/?cat=clothing-dresses"
index_pages: 
  - "/men/search/"
  - "/women/search/"
detail_pages: "/product/"
attributes: 
  - name: "title"
    selector: "span._3mRKt::text"
    processors:
      - "join"
      - "strip"
  - name: "sale_price"
    selector: "div.eP0wn._26-lJ._28iFq::text"
    processors:
      - "join"
      - "strip"
    regex: "[,.0-9]+"
  - name: "full_price"
    selector: "span._2plVT._35rbh::text"
    regex: "[,.0-9]+"
  - name: "description"
    selector: "div._34YUR._1K7NF > span::text"
    processors:
      - "strip"
  - name: "brand"
    selector: "h1._1psEi > a::text"
    processors:
      - "strip"
  - name: "gender"
    selector: "li._1Hb_0:nth-child(1) > a > span::text"
    processors:
      - "strip"
  - name: "category"
    selector: "li._1Hb_0:nth-child(3) > a > span::text"
    processors:
      - "strip"
  - name: "sub_category"
    selector: "li._1Hb_0:nth-child(4) > a > span::text"
    processors:
      - "strip"
  - name: "sub_sub_category"
    selector: "li._1Hb_0:nth-child(5) > a > span::text"
    processors:
      - "strip"
  - name: retailer
    selector: "a.YLflv > strong::text"
    processors:
      - strip
